// What I want to achive: build a message generator program
// 1. every time a user runs a program, they should get a new, randomized nonsensical joke.
// 2. the message that it outputs should be made up of at least three different pieces of data.

const yourSign = [
    "Your sign is Aries.",
    "Your sign is Taurus.",
    "Your sign is Gemini.",
    "Your sign is Cancer.",
    "Your sign is Leo.",
    "Your sign is Virgo.",
    "Your sign is Libra.",
    "Your sign is Scorpio.",
    "Your sign is Sagittarius.",
    "Your sign is Capricorn.",
    "Your sign is Aquarius.",
    "Your sign is Pisces.",
    "Your sign is the moon.",
    "Your sign is Mercury.",
    "Your sign is Venus.",
    "Your sign is Mars.",
    "Your sign is Jupiter.",
    "Your sign is Saturn.",
    "Your sign is Neptune.",
    "Your sign is Uranus.",
    "Your sign is Pluto.",
    "Your sign is the rising sun.",
    "Your sign is the North Star.",
    "Your sign is the crescent moon.",
    "Your sign is Orion.",
    "Your sign is the comet.",
    "Your sign is the eclipse.",
    "Your sign is the constellation Phoenix.",
    "Your sign is the morning star.",
    "Your sign is the void.",
    "Your sign is the cosmic alignment.",
    "Your sign is the supernova.",
    "Your sign is the black hole.",
    "Your sign is the asteroid belt.",
    "Your sign is the Milky Way.",
    "Your sign is the nebula.",
    "Your sign is the solar flare.",
    "Your sign is the meteor shower.",
    "Your sign is the retrograde.",
    "Your sign is the equinox.",
    "Your sign is the solstice.",
    "Your sign is the dark moon.",
    "Your sign is the aurora.",
    "Your sign is the celestial sphere.",
    "Your sign is the cosmic dust.",
    "Your sign is the red giant.",
    "Your sign is the white dwarf.",
    "Your sign is the pulsar.",
    "Your sign is the gravity well.",
    "Your sign is the infinite."
];

const yourHaving = [
    "You are having good luck.",
    "You are having a transformative period.",
    "You are having unexpected opportunities.",
    "You are having challenges with communication.",
    "You are having financial growth.",
    "You are having romantic tensions.",
    "You are having creative breakthroughs.",
    "You are having family conflicts.",
    "You are having career setbacks.",
    "You are having spiritual awakenings.",
    "You are having health improvements.",
    "You are having social success.",
    "You are having emotional turbulence.",
    "You are having mental clarity.",
    "You are having travel opportunities.",
    "You are having trust issues.",
    "You are having abundance.",
    "You are having self-doubt.",
    "You are having passionate encounters.",
    "You are having life-changing revelations.",
    "You are having mysterious dreams.",
    "You are having power struggles.",
    "You are having moments of clarity.",
    "You are having technological breakthroughs.",
    "You are having karmic encounters.",
    "You are having creative blocks.",
    "You are having renewed energy.",
    "You are having diplomatic victories.",
    "You are having existential questions.",
    "You are having professional recognition.",
    "You are having forbidden desires.",
    "You are having ancestral connections.",
    "You are having restless nights.",
    "You are having enlightening conversations.",
    "You are having material losses.",
    "You are having spiritual tests.",
    "You are having rebellious urges.",
    "You are having nostalgic moments.",
    "You are having powerful allies.",
    "You are having hidden enemies.",
    "You are having prophetic visions.",
    "You are having intense passions.",
    "You are having moral dilemmas.",
    "You are having lucky coincidences.",
    "You are having reality checks.",
    "You are having artistic inspiration.",
    "You are having philosophical debates.",
    "You are having cosmic downloads.",
    "You are having time distortions.",
    "You are having parallel experiences."
];

const youShould = [
    "You should trust no one.",
    "You should embrace change.",
    "You should listen to your intuition.",
    "You should take calculated risks.",
    "You should avoid confrontations.",
    "You should speak your truth.",
    "You should let go of the past.",
    "You should invest in yourself.",
    "You should reconnect with old friends.",
    "You should be patient.",
    "You should follow your heart.",
    "You should question everything.",
    "You should stay grounded.",
    "You should seek adventure.",
    "You should practice gratitude.",
    "You should set boundaries.",
    "You should trust the process.",
    "You should take a leap of faith.",
    "You should focus on self-care.",
    "You should be open to love.",
    "You should dance in the rain.",
    "You should challenge authority.",
    "You should meditate at midnight.",
    "You should burn old letters.",
    "You should learn a new language.",
    "You should confront your fears.",
    "You should plant something.",
    "You should write your story.",
    "You should disconnect from technology.",
    "You should forgive someone.",
    "You should take the scenic route.",
    "You should say what you mean.",
    "You should start a revolution.",
    "You should honor your ancestors.",
    "You should break the rules.",
    "You should seek solitude.",
    "You should make amends.",
    "You should laugh more often.",
    "You should question your beliefs.",
    "You should embrace the chaos.",
    "You should protect your energy.",
    "You should take nothing personally.",
    "You should follow the signs.",
    "You should release expectations.",
    "You should create something beautiful.",
    "You should tell the truth.",
    "You should explore the unknown.",
    "You should trust your instincts.",
    "You should sleep under the stars.",
    "You should become who you are."
];

function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

console.log(`${yourSign[getRandomInt(0, yourSign.length - 1)]}
${yourHaving[getRandomInt(0, yourHaving.length - 1)]}
${youShould[getRandomInt(0, youShould.length - 1)]}`);